title: James Sundquist
description: Lecturer <br> Jackson School of Global Affairs <br> Yale University
logo: /assets/img/headshot2.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
