title: James Sundquist
description: Principal Research Scientist <br> NSI, Inc.
logo: /assets/img/Sundquist_headshot copy.jpeg
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
paginate: 5
paginate_path: "/blog/page:num"
